
NAME =		$(PWD)/nibbler

SRC =		src

SOURCES =	$(SRC)/GameEngine/GameEngine.cpp \
		$(SRC)/GameEngine/Events/InputEvent.cpp \
		$(SRC)/GameEngine/Events/Event.cpp \
		$(SRC)/GameEngine/Events/EventHandler.cpp \
		$(SRC)/GameEngine/Events/EventDispatcher.cpp \
		$(SRC)/GameEngine/Core/Core.cpp \
		$(SRC)/GameEngine/CoreInput.cpp \
		$(SRC)/GameEngine/Scene.cpp \
		$(SRC)/GameEngine/Renderer.cpp \
		$(SRC)/GameEngine/SceneManager.cpp \
		$(SRC)/GameEngine/GameScreen.cpp \
		$(SRC)/GameEngine/GameScreenManager.cpp \
		$(SRC)/GameEngine/Core/CoreServices.cpp \
		$(SRC)/GameEngine/Entities/BaseEntity.cpp \
		$(SRC)/GameEngine/Entities/ShapeEntity.cpp \


SOURCES +=	$(SRC)/main.cpp \
		$(SRC)/NibblerCore.cpp \

OBJS =		$(SOURCES:.cpp=.o)

LDFLAGS =	-ldl -rdynamic

CXX =		g++

INCLUDES =	-I./$(SRC) -I./$(SRC)/GameEngine/

CXXFLAGS =	$(INCLUDES) -ansi -pedantic -Wextra -Wall


$(NAME):	$(OBJS)
		$(CXX) $(OBJS) -o $@ $(LDFLAGS)

.cpp.o:
		$(CXX) -c $< -o $@ $(CXXFLAGS)

clean:
		$(RM) $(OBJS)

fclean: 	clean
		$(RM) $(NAME)

re:		fclean $(NAME)

.PHONY: 	all clean fclean re
